vlsi.core:
  synthesis_tool_path: [/fs1/eecg/vaughn/morestep/hammer/src/hammer-vlsi/hammer-cadence-plugins/synthesis]
  synthesis_tool: genus
  
  par_tool_path: [/fs1/eecg/vaughn/morestep/hammer/src/hammer-vlsi/hammer-cadence-plugins/par]
  par_tool: innovus

  #technology
  technology: asap7


# synthesis settings
synthesis:
  inputs.input_files: [ /fs1/eecg/vaughn/morestep/COFFE/input_files/network_on_chip/router/src ]
  inputs.top_module: router_wrap
  inputs.hdl_search_paths: []
  clock_gating_mode: "empty"
  

# place and route settings
# par.innovus:
#   floorplan_mode: "manual"
#   par.innovus.floorplan_script_contents: "create_floorplan -core_margins_by die -flip f -die_size_by_io_height max -site asap7sc7p5t -keep_shape_density 70"
par.innovus.design_flow_effort: "standard"

vlsi.inputs:
  power_spec_mode: "auto"
  power_spec_type: "cpf"
  clocks : [
    {
      name: "clk",
      period: "0.571 ns",
    }
  ]
  placement_constraints:
  - path: router_wrap
    type: toplevel
    x: 100
    y: 100
    #width: 1100
    #height: 1100
    width: 3500
    height: 3500
    
    margins:
      left: 0
      right: 0
      top: 0
      bottom: 0
  # VCR TOP
  - path: router_wrap/genblk2.vcr
    type: hierarchical
    x: 100.0
    y: 100.0
    width: 340.0
    height: 340.0
    master: vcr_top_buffer_size16_num_message_classes2_num_resource_classes1_num_vcs_per_class1_num_routers_per_dim8_num_dimensions2_num_nodes_per_router1_connectivity0_packet_format2_flow_ctrl_type0_flow_ctrl_bypass0_max_payload_length4_min_payload_length0_enable_link_pm1_flit_data_width64_error_capture_mode1_restrict_turns1_routing_type0_dim_order0_fb_regfile_type0_fb_mgmt_type0_fb_fast_peek1_disable_static_reservations0_explicit_pipeline_register1_gate_buffer_write0_elig_mask1_vc_alloc_type0_vc_alloc_arbiter_type0_sw_alloc_type0_sw_alloc_arbiter_type0_sw_alloc_spec_type3_crossbar_type1_reset_type0
  # NORTH WEST CORNER
  - path: router_wrap/gen_port_regs[1].channel_in_ff
    type: hierarchical
    x: 43.0
    #y: 920.0
    y: 3300.0
    width: 25
    height: 33
    master:  c_dff_width68_reset_type0_3266
  # NORTH WEST CORNER
  - path: router_wrap/gen_port_regs[1].channel_out_ff
    type: hierarchical
    x: 73.0
    # y: 920.0
    y: 3300.0
    width: 25
    height: 33
    master: c_dff_width68_reset_type0_3265
  # SOUTH EAST CORNER
  - path: router_wrap/gen_port_regs[2].channel_in_ff
    type: hierarchical
    # x: 927.0
    x: 3307.0 
    y: 41.0
    width: 29
    height: 27
    master: c_dff_width68_reset_type0_3264
  # SOUTH EAST CORNER
  - path: router_wrap/gen_port_regs[2].channel_out_ff
    type: hierarchical
    # x: 927.0
    x: 3307.0 
    y: 73.0
    width: 29
    height: 27
    master: c_dff_width68_reset_type0_3263

  pin_mode: generated
  pin.generate_mode: semi_auto
  pin.assignments: [
    {pins: "*", layers: ["M5", "M7"]}
  ]

