
designs:
  # base config is the hammer config file which is used as a template for designs which will be swept over
  - base_config_path: ~/rad_gen/input_designs/strtx_10_like_dsp/strtx_10_dsp_config.yml
    # These two args are required for each run of hammer flow
    top_level_module: FMULT
    rtl_dir_path:  ~/rad_gen/input_designs/strtx_10_like_dsp/baseline_dsp
      #type: "vlsi_params"
    flow_threads: 2
    params:
      {
        "clk_periods": [1.33, 1.11]
      }
