

designs: 
  [{
      top_level: router_wrap_bk,
      report_search_path: ~/rad_gen,
      params: [
      "num_vcs",
      "num_ports",
      "flit_data_width",
      "buffer_size",
      ],
    }
  ]

  
