# synthesis settings
synthesis:
  inputs.input_files: [ 
    ~/rad_gen/unit_tests/inputs/asic_dse/inv/rtl/inv.sv,
   ]
  inputs.top_module: inv
  inputs.hdl_search_paths: [ ~/rad_gen/unit_tests/inputs/asic_dse/inv/rtl ]
  clock_gating_mode: "empty"
  

# place and route settings
par.innovus:
  floorplan_mode: "manual"
  floorplan_script_contents: "create_floorplan -core_margins_by die -flip f -die_size_by_io_height max -site asap7sc7p5t -stdcell_density_size {1.0 0.7 10 10 10 10}"
  design_flow_effort: "express"

vlsi.inputs:
  power_spec_mode: "auto"
  power_spec_type: "cpf"
  clocks : [
    {
      name: "clk",
      period: "2 ns",
    }
  ]
  placement_constraints:
  - path: inv
    type: toplevel
    x: 20
    y: 20
    width: 500
    height: 500
    margins:
      left: 0
      right: 0
      top: 0
      bottom: 0

