par.innovus.design_flow_effort: standard
synthesis:
  clock_gating_mode: empty
  inputs.input_files:
  - input_designs/sram/rtl/test_sram/sram.sv
  inputs.top_module: sram_wrapper
vlsi.core:
  par_tool: innovus
  par_tool_path:
  - /fs1/eecg/vaughn/morestep/hammer/src/hammer-vlsi/hammer-cadence-plugins/par
  sram_generator_tool: sram_compiler
  sram_generator_tool_path:
  - /fs1/eecg/vaughn/morestep/hammer/src/hammer-vlsi/technology/asap7
  sram_generator_tool_path_meta: append
  synthesis_tool: genus
  synthesis_tool_path:
  - /fs1/eecg/vaughn/morestep/hammer/src/hammer-vlsi/hammer-cadence-plugins/synthesis
  technology: asap7
vlsi.inputs:
  clocks:
  - name: RW0_clk
    period: 0.0 ns
  pin.assignments:
  - layers:
    - M5
    - M7
    pins: '*'
  pin.generate_mode: semi_auto
  pin_mode: generated
  placement_constraints:
  - height: 400
    margins:
      bottom: 0
      left: 0
      right: 0
      top: 0
    path: sram_wrapper
    type: toplevel
    width: 400
    x: 0
    y: 0
  - master: SRAM1RW16x8
    orientation: r0
    path: sram_wrapper/genblk.mem_0_0
    top_layer: M4
    type: hardmacro
    x: 20
    y: 20
  power_spec_mode: auto
  power_spec_type: cpf
  sram_parameters: /fs1/eecg/vaughn/morestep/rad_gen/input_designs/sram/configs/mem_params.json
  sram_parameters_meta:
  - transclude
  - json2list
