vlsi.core:
  synthesis_tool_path: [/fs1/eecg/vaughn/morestep/hammer/src/hammer-vlsi/hammer-cadence-plugins/synthesis]
  synthesis_tool: genus
  
  par_tool_path: [/fs1/eecg/vaughn/morestep/hammer/src/hammer-vlsi/hammer-cadence-plugins/par]
  par_tool: innovus

  #technology
  technology: asap7

  max_threads: 2


# synthesis settings
synthesis:
  inputs.input_files: [ input_designs/alu/rtl/src/alu.sv ]
  inputs.top_module: alu_ver
  inputs.hdl_search_paths: [ /fs1/eecg/vaughn/morestep/rad_gen/input_designs/alu/rtl/src ]
  clock_gating_mode: "empty"
  

# place and route settings
par.innovus:
  floorplan_mode: "manual"
  floorplan_script_contents: "create_floorplan -core_margins_by die -flip f -die_size_by_io_height max -site asap7sc7p5t -stdcell_density_size {1.0 0.7 10 10 10 10}"
  design_flow_effort: "express"

vlsi.inputs:
  power_spec_mode: "auto"
  power_spec_type: "cpf"
  clocks : [
    {
      name: "clk",
      period: "2 ns",
    }
  ]
  placement_constraints:
  - path: alu_ver
    type: toplevel
    x: 20
    y: 20
    width: 500
    height: 500
    margins:
      left: 0
      right: 0
      top: 0
      bottom: 0

